### ISSUE TITLE
Improper Use of HTML5 Self Closing Tags

### ISSUE THREAD

**Issue by mayankbpatel** [flukeout/restaurant#131] opened 2016-10-08 17:47 UTC
I noticed that many examples in CSS Diner make use of self-closing tags that lead to confusion.

Modern browsers view self-closing tags (except for `<br/>`) as errors and will treat the self-closing tag as a start tag.  This leads to nesting of adjacent tags and changes the structure and semantics of the rendered HTML.

For example, consider this snippet from level 17:

```
<div class="table">
  <plate id="fancy">
    <apple class="small"/>
  <plate />
  <plate />
  <plate>
    <orange class="small"/>
    <orange />
  <plate />
  <pickle class="small"/>
</div>
```

The browser actually interprets this as:

```
<div class="table">
  <plate id="fancy">
    <apple class="small">
      <plate>
        <plate>
          <plate>
            <orange class="small">
              <orange>
                <plate>
                  <pickle class="small">
                  </pickle>
                </plate>
              </orange>
            </orange>
          </plate>
        </plate>
      </plate>
    </apple>
  </plate>
</div>
```

Notice how the rendered HTML now communicates a different intent than originally desired.

I think it's best practice to explicitly close all tags and save the self-closing short-cut for `<br/>`.

For reference:  http://stackoverflow.com/questions/3558119/are-self-closing-tags-valid-in-html5#3558200

**Comment by flukeout** [comment] 2016-10-20 18:36
Thanks for pointing this out! Initially I went with the self-closing style to reduce the clutter in the HTML editor. I don't want to promote bad habits so I think I'll need to change this.

**Comment by isti115** [comment] 2017-01-29 21:47
Just noticed this exact same thing the other day when I introduced CSS to my girlfriend using the site. Are you still planning on fixing this yourself, or should I file a pull request instead?

**Comment by flukeout** [comment] 2017-01-30 06:26
Thanks for re-visiting @Isti115 - if you'd be willing to make a PR, I'd really appreciate it.

Let me know if you need any help or have questions. I think it should just be a matter of changing the markup structure in ``levels.js``

**Comment by isti115** [comment] 2017-02-04 01:57
I just had some time to look at this and realized that the markup in `levels.js` is completely fine, it only renders weird on the site. For example when looking at the 4th task the plate looks like this the file:
```
<plate>
  <apple/>
</plate>
```
while on the site it displays this:
```
<plate>
  <apple/>
<plate/>
```

If I will have more time, I'll try to figure out what could be causing this.

**Comment by flukeout** [comment] 2017-02-06 18:02
Oh wow, that's a huge oversight on my part!
I'm generating markup visible in the "Editor Panel" line by line based on what is in ``levels.js``, it's not using that markup directly.

I think what's happening is I've defined a closing tag syntax in the same way as a self closing tag, and it's just using that format in both circumstances! Oops!

**Comment by flukeout** [comment] 2017-02-06 18:27
I think it's happening here..

https://github.com/flukeout/css-diner/blob/develop/js/restaurant.js#L550

``wrapperEl.append("&lt;" + elName +  "/&gt;");``

should be...

``wrapperEl.append("&lt;/" + elName +  "&gt;");``

**Comment by isti115** [comment] 2017-02-09 23:12
Should I still issue a pull request, or are you planning on changing the suggested line yourself now that you have found the cause? (I think that it would be a lot easier to test for you, so it doesn't make much sense for me to change it without even being able to try it out.)

**Comment by flukeout** [comment] 2017-02-09 23:52
I'll make the change @Isti115 - thank you for the reminder.

**Comment by isti115** [comment] 2017-02-13 23:23
I just had a few minutes and seen that there were still no changes to `restaurant.js`, so I created the [pull request](https://github.com/flukeout/css-diner/pull/141) anyway.

**Comment by isti115** [comment] 2017-02-17 00:17
Thanks for merging! :)
I think that you can now close this issue as well.

**Comment by flukeout** [comment] 2017-02-17 17:00
You got it. Oh yeah, if you put a "Fixes #XXXX" where XXXX is the issue number in your Pull Request, it will automatically close the related issue when the PR is merged!

**Closed as completed** 2017-02-17 17:00 UTC

**Comment by isti115** [comment] 2017-02-18 15:00
Thank you very much for the information! :) I didn't know that before, but it sounds pretty useful!
